name: dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest # [self-hosted, linux, x64]

    env:
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
        DOTNET_ROOT: ${{ github.workspace }}/dotnet  # Define a writable directory for .NET
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: SonarCloud Tools
      run: dotnet tool install --global dotnet-sonarscanner

    - name: SonarCloud Scanner
      run:  dotnet sonarscanner begin /o:"wangkanai-github" /k:"github_wangkanai" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    - name: Install npm
      run: |
        npm install -g rimraf
      shell: bash

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test  --no-build --verbosity normal

    - name: SonarCloud Coverage
      run:  dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
