# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        
    - name: Install npm
      run: |
        npm install -g rimraf
      shell: bash

    - name: Install dotnet-coverage tool
      run: dotnet tool install --global dotnet-coverage

    - name: Add .NET tools to PATH
      run: echo "::add-path::$(echo $HOME/.dotnet/tools)"      
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet coverage collect "dotnet test" -f xml -o "coverage.xml"
