name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          args:  --ide,QDNET,--apply-fixes,--save-report,--baseline,qodana.sarif.json, #--diff-start,<GIT_START_HASH>,--diff-end,<GIT_END_HASH>
          push-fixes: pull-request
          pr-mode: false
          cache-default-branch-only: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1880801860 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
      - name: Archive coverage data # Archive data for use by Qodana
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-coverage-data
          path: .qodana/code-coverage
