name: qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest # [self-hosted, linux, x64]
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install npm
        run: |
          npm install -g rimraf
        shell: bash
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --verbosity minimal --tl
      - name: Coverage
        run: dotnet test --no-build --verbosity minimal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./qodana/
      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-coverage-data
          path: ${{ runner.temp }}/**/qodana/*
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1880801860 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
        with:
          args: --baseline,qodana.sarif.json
          pr-mode: false
          push-fixes: pull-request
          cache-default-branch-only: false
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
